### PR TITLE
Add license, update build scripts, and add OBS support

### LINKED ISSUE #1: License missing
Continuation of https://github.com/nodevel/harbour-defender/issues/10

@peterleinchen, Please suggest which license do you want to have and either set it yourself or, with your approval, I can add license as a part of PR for Chum

### PR DESCRIPTION
**Pull request by rinigus**
This PR adds 
- license - GPLv3
- revamps build scripts 
- adds Chum section

As you have been using SPEC directly (as far as I can tell), I have dropped YAML and cleaned up SPEC accordingly. With qmake changes, now it supports building from different directories, not just as in SDK. That was required for OBS building.

Finally, Chum section has been added. 

Please review. If review is fine and merged then I can try to get it compiled for all Chum platforms and add to Chum. Current OBS build is at https://build.sailfishos.org/package/show/home:rinigus:sandbox/harbour-defender

Fixes #1

### CODE REVIEW

**Comment by rinigus** [comment]
@peterleinchen: ping. Please review. If accepted, I'll be able to proceed with submitting it to Chum.

**Comment by peterleinchen** [comment]
@rinigus

Sorry for delay, but as mentioned I am not able to be online that much.
Will try to review/accept asap.

Sorry and thanks for your efforts
Peter 


On Thursday, 27 January 2022, rinigus wrote:
> @peterleinchen: ping. Please review. If accepted, I'll be able to proceed with submitting it to Chum.
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/peterleinchen/harbour-defender/pull/2#issuecomment-1023578092
> You are receiving this because you were mentioned.
> 
> Message ID: ***@***.***

-- 
Peter Leinchen

Sent from my mobile device

**Comment by rinigus** [comment]
@peterleinchen: thank  you very much for looking into it. Just wanted to be sure that it will not stay forgotten :). 

Looking forward for your review.

**Comment by rinigus** [comment]
Ping! Any progress with it?

**Comment by peterleinchen** [comment]
Pong.

I am sorry, but I did (almost) not touch any computer the last weeks.

I do know and remember, seeing the mail open in my mailbox. And will try to do so asap, but no promise.

Please feel free to poing me once more.

Best
Peter

On Sunday, 6 February 2022, rinigus wrote:
> Ping! Any progress with it?
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/peterleinchen/harbour-defender/pull/2#issuecomment-1030777499
> You are receiving this because you were mentioned.
> 
> Message ID: ***@***.***

-- 
Peter Leinchen

Sent from my mobile device

**Comment by rinigus** [comment]
Hi! This is a reminder  - hopefully you can take a look into these changes soon.

**Comment by rinigus** [comment]
Hi! Any hope to get that reviewed? :)

**Comment by peterleinchen** [comment]
I do hope so ;)

At home again and looking to that this week (hooefully :)

Best 

On Sunday, 20 February 2022, rinigus wrote:
> Hi! Any hope to get that reviewed? :)
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/peterleinchen/harbour-defender/pull/2#issuecomment-1046249904
> You are receiving this because you were mentioned.
> 
> Message ID: ***@***.***

-- 
Peter Leinchen

Sent from my mobile device

**Comment by rinigus** [comment]
Ping, please review

**Comment by rinigus** [comment]
@peterleinchen, please review this PR

**Comment by peterleinchen** [comment]
Rinigus,

very very sorry for looong delay!
I did review but and can only tell about stuff I know (or think I know) ;)
and this lokks fine regarding yaml and changes 
cannot say about chum additions and the pro file changes.

But I think this is fine.
I merged it (now :)

Thank you 
Peter

**Comment by rinigus** [comment]
Great! I will proceed then with pushing it to Chum. Will test how it goes there and then probably would ask you to make new release for cleaner builds. Such tag is not needed yet, let me test it first :)

**Comment by peterleinchen** [comment]
Sure :)

On Saturday, 12 March 2022, rinigus wrote:
> Great! I will proceed then with pushing it to Chum. Will test how it goes there and then probably would ask you to make new release for cleaner builds. Such tag is not needed yet, let me test it first :)
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/peterleinchen/harbour-defender/pull/2#issuecomment-1065892196
> You are receiving this because you modified the open/close state.
> 
> Message ID: ***@***.***

-- 
Peter Leinchen

Sent from my mobile device

**Comment by rinigus** [comment]
All looks to be fine, as far as I can see. Would you mind to tag a new release and then I can push it to Chum proper. Current Chum testing builds are at https://build.sailfishos.org/package/show/sailfishos:chum:testing/harbour-defender and, as you can see, have a rather long version :) . That would be fixed as soon as you tag and I restart rebuilds.

**Comment by peterleinchen** [comment]
Wow.
A "bit" faster than me :D

I changed version in spec to 0.6.0 and set new tag 0.6.0.
Let's try...


P.S.:
Do I need (should have) an account on OBS?
Sign up is disabled.



On Sunday, 13 March 2022, rinigus wrote:
> All looks to be fine, as far as I can see. Would you mind to tag a new release and then I can push it to Chum proper. Current Chum testing builds are at https://build.sailfishos.org/package/show/sailfishos:chum:testing/harbour-defender and, as you can see, have a rather long version :) . That would be fixed as soon as you tag and I restart rebuilds.
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/peterleinchen/harbour-defender/pull/2#issuecomment-1066046939
> You are receiving this because you modified the open/close state.
> 
> Message ID: ***@***.***

-- 
Peter Leinchen

Sent from my mobile device

**Comment by rinigus** [comment]
@peterleinchen: yes, you need to get an account at OBS. For that, ping "lbt" and "Keto" and ask for account on IRC #sailfishos channel. 

When you get used to OBS, it is very simple and convenient.

I have updated the build and will push it now to Chum main repository. Thanks for tagging!

**Review by peterleinchen — COMMENTED** [review]
@peterleinchen reviewed
(No idea, why this review was requested by myself...?)

**Pull request merged**
